### ISSUE TITLE
Using TypeScript Refactor publish to 2.2 version

### ISSUE THREAD

**Issue by medz** [medz/webpack-laravel-mix-manifest#12]
- [x] Using TypeScript refactor
- [x] Add Jest tests
- [x] More CI build

**Comment by medz** [comment]
@ankurk91 I mistakenly put the 2.2.0-dev.0 on the release tag. I passed the test and the wrong version was upgraded. Although the APIs of version 2.2 have not been changed, the entry method has been changed. It may cause you trouble, so sorry!

**Comment by ankurk91** [comment]
@medz 
Thanks for notification

**Comment by medz** [comment]
@ankurk91 Because of my error, I used all the time today to get the new version to work.

There is basically no difference between the 2.1 version and the 2.2 version. Here I give the correct migration guide 👉 [releases/v2.2.0](https://github.com/medz/webpack-laravel-mix-manifest/releases/tag/v2.2.0)

## the difference

- 2.1 Use default export, 2.2 Use module export
- Version 2.2 is completely refactored using TypeScript
- Version 2.2 now exports both cjs and mjs modules

**Comment by ankurk91** [comment]
@medz 

Please consider release a major version when such breaking changes is made.
I was expecting `v3.0.0`, since `2.2.0` brings breaking change in the way we import the package.

I have updated my package to reflect the new changes in your package.

Thanks for maintaining this awesome package. :)
